# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'eb2d3ad9-9b3f-4446-804d-32bea1b2975e'
  imageRepository: 'imagescan'
  containerRegistry: 'tomerplay'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:  
  - job: BuildAndPush
    displayName: BuildAndPush
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        addPipelineData: false
        tags: |
          $(tag)
          latest

  - job: Delay
    displayName: Delay
    pool: Server
    dependsOn: 
    - BuildAndPush
    condition: succeeded()
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '5'

  - job: ImageScan
    displayName: ImageScan
    pool:
      vmImage: $(vmImageName)
    dependsOn: 
    - BuildAndPush
    - Delay
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Rome ILDC – Detection Playground (409111bf-3097-421c-ad68-a44e716edf58)'
        scriptType: 'pscore'
        scriptLocation: 'scriptPath'
        scriptPath: '$(Build.SourcesDirectory)/cicdAz.ps1'
        arguments: '-registryName $(containerRegistry) -repository $(imageRepository) -tag $(tag)'
      
